<?xml version="1.0" encoding="utf-8"?><Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDefaultItems>False</EnableDefaultItems>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-BlazorDemo-CRM-53bc9b9d-9d6a-45d4-8429-2a2761773502</UserSecretsId>
    <RootNamespace>BlazorDemo.CRM</RootNamespace>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="DevExtreme.AspNet.Data" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlazorDemo.CRM.Client\BlazorDemo.CRM.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.AIIntegration" VersionOverride="26.1.3" />
    <PackageReference Include="DevExpress.Blazor" VersionOverride="26.1.3" />
    <PackageReference Include="DevExpress.Drawing.Skia" VersionOverride="26.1.3" />
    
    
    
    
    
    
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="obj\**\*.cs" />
    <Content Include="Components\**\*.razor" />
    <Content Include="Components\**\*.css" />
    <Content Include="wwwroot\**\*.*" />
    <Content Include="*.json" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
